<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE documentation
	[
		<!ELEMENT documentation (instructions)>
		<!ELEMENT instructions (instruction*)>
		<!ELEMENT instruction (name,parameters,description,exemple, opcode)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT parameters (parameter*)>
		<!ELEMENT parameter (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT exemple (#PCDATA)>
		<!ELEMENT opcode (#PCDATA)>
	]>

<documentation>
	<instructions>
		<instruction>
			<name>aaload</name>
			<parameters>
			</parameters>
			<description>Cette instruction charge une réference d'un tableau dans la stack. L'instruction ne prend rien en paramètre.</description>
			<exemple>aaload</exemple>
			<opcode>50</opcode>
		</instruction>
		<instruction>
			<name>aastore</name>
			<parameters>
			</parameters>
			<description>Cette instruction  une réference dans un tableau. L'instruction ne prend rien en paramètre.</description>
			<exemple>aastore (Si une tableau de réference est chargé précédemment, la référence sera stockée dans le tableau).</exemple>
			<opcode>83</opcode>
		</instruction>
		<instruction>
			<name>aconst_null</name>
			<parameters>
			</parameters>
			<description>Cette instruction stocke une réference de valeur null. L'instruction ne prend rien en paramètre.</description> 
			<exemple>aconst_null</exemple>
			<opcode>1</opcode>
		</instruction>
		<instruction>
			<name>aload</name>
			<parameters>
				<parameter>index</parameter>
			</parameters>
			<description>Cette instruction charge une réference #index donné en paramètre dans la stack. Index est de type unsigned byte.</description>
			<exemple>aload</exemple>
			<opcode>25</opcode>
		</instruction>
		<instruction>
			<name>aload_0</name>
			<parameters>
			</parameters>
			<description>Cette instruction charge une référence depuis une variable locale 0 dans la stack. Cette instruction ne prend rien en paramètre.</description>
 
			<exemple>aload_0</exemple>
			<opcode>42</opcode>
		</instruction>
		<instruction>
			<name>aload_1</name>
			<parameters>
			</parameters>
   
			<description>Cette instruction charge une référence depuis une variable locale 1 dans la stack. Cette instruction ne prend rien en paramètre.</description>
 
			<exemple>aload_1</exemple>
			<opcode>43</opcode>
		</instruction>
		<instruction>
			<name>aload_2</name>
			<parameters>
			</parameters>
    
			<description>Cette instruction charge une référence depuis une variable locale 1 dans la stack. Cette instruction ne prend rien en paramètre.2</description>
 
			<exemple>aload_2</exemple>
			<opcode>44</opcode>
		</instruction>
		<instruction>
			<name>aload_3</name>
			<parameters>
			</parameters>
    
			<description>Cette instruction charge une référence depuis une variable locale 3 dans la stack. Cette instruction ne prend rien en paramètre.</description>
 
			<exemple>aload_3</exemple>
			<opcode>45</opcode>
		</instruction>
		<instruction>
			<name>anewarray</name>
			<parameters>
				<parameter>indexbyte1</parameter>
				<parameter>indexbyte2</parameter>
			</parameters>
    
			<description>Cette instruction crée un nouveau tableau de références.</description>
 
			<exemple>anewarray</exemple>
			<opcode>189</opcode>
		</instruction>
		<instruction>
			<name>areturn</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction retourne une référence d'une méthode invoquée. Cette méthode ne prend aucun paramètre.</description>
			<exemple>areturn (Précédé d'un invokestatic par exemple retourne la référence).</exemple>
 
			<opcode>176</opcode>
		</instruction>
		<instruction>
			<name>arraylength</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction permet de retourner la taille d'un tableau sous forme d'un int dans la stack. Cette instruction ne prend pas de paramètre.</description>
			<exemple>arraylength (Admettons qu'une instruction getstatic appelant une méthode static affiche un tableau arraylength nous permet de sauvegarder sa taille. Nous pouvons donc la stocker avec un istore_0 par exemple).</exemple>
  
 
			<opcode>190</opcode>
		</instruction>
		<instruction>
			<name>astore</name>
			<parameters>
				<parameter>index</parameter>
			</parameters>
  
  
			<description>Cette instruction stocke une référence dans une variable locale donnée en paramètre #index.</description>
 
			<exemple>astore</exemple>
			<opcode>58</opcode>
		</instruction>
		<instruction>
			<name>astore_0</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction stocke une référence dans la variable locale astore_0. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>astore_0 (Admettons qu'une instruction de chargement d'un référence d'un tableau par exemple est effectué avant astore_0 se chargera de stocker cette référence.</exemple>
			<opcode>75</opcode>
		</instruction>
		<instruction>
			<name>astore_1</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction stocke une référence dans la variable locale astore_1. Cette instruction ne prend pas de paramètre.</description>
   
			<exemple>astore_1 (Admettons qu'une instruction de chargement d'un référence d'un tableau par exemple est effectué avant astore_1 se chargera de stocker cette référence.</exemple>
			<opcode>76</opcode>
		</instruction>
		<instruction>
			<name>astore_2</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction stocke une référence dans la variable locale astore_2. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>astore_2 (Admettons qu'une instruction de chargement d'un référence d'un tableau par exemple est effectué avant astore_2 se chargera de stocker cette référence.</exemple>
			<opcode>77</opcode>
		</instruction>
		<instruction>
			<name>astore_3</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction stocke une référence dans la variable locale astore_3. Cette instruction ne prend pas de paramètre.</description>
   
			<exemple>astore_3 (Admettons qu'une instruction de chargement d'un référence d'un tableau par exemple est effectué avant astore_3 se chargera de stocker cette référence.</exemple>
			<opcode>78</opcode>
		</instruction>
		<instruction>
			<name>athrow</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction lève une exception ou une erreur. Cette instruction ne prend pas de paramètre.</description>
   
			<exemple>athrow (Précédé d'un invokespecial qui retourne un RuntimeException par exemple).</exemple>
			<opcode>191</opcode>
		</instruction>
		<instruction>
			<name>baload</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction charge un byte ou un boolean depuis un tableau. Cette instruction ne prend pas de paramètre.</description>
			<exemple>baload (Précédé d'un aload par exemple charge un byte ou un boolean du tableau. Le tableau chargé doit être du type attendu).</exemple>
  
			<opcode>51</opcode>
		</instruction>
		<instruction>
			<name>bastore</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction stocke un byte ou un boolean dans un tableau. Cette instruction ne prend pas de paramètre.</description>
			<exemple>bastore (Précédé d'une instruction de chargemennt par exemple stocke un byte ou un boolean dans un tableau. Le tableau chargé doit être du type attendu).</exemple>
 
			<opcode>84</opcode>
		</instruction>
		<instruction>
			<name>bipush</name>
			<parameters>
				<parameter>n</parameter>
			</parameters>
  
			<description>Cette instruction stocke la valeur en paramètre "n" dans la stack de type byte vers int. "n" appartient à l'intervalle [-128;127]</description>
			<exemple>bipush 100 (stocke 100 dans la stack. Peut être utilisé par exemple pour vérifier la condition d'un if. De ce fait bipush peut être suivi de l'instruction if_quelqueChose ou peut être stocké dans un istore_0 par exemple).</exemple>
 
			<opcode>16</opcode>
		</instruction>
		<instruction>
			<name>breakpoint</name>
			<parameters>
			</parameters>
			<description>Cette instrcution montre tout simplement un point d'arrêt, breakpoint ou bp effectuée par l'intermédiaire du déboggueur. Cette instruction ne se raccorde à aucune ligne de code du java.</description>
			<exemple>breakpoint</exemple>
			<opcode>202</opcode>
		</instruction>
		<instruction>
			<name>caload</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction charge un char d'un tableau. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>caload</exemple>
			<opcode>52</opcode>
		</instruction>
		<instruction>
			<name>castore</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction stocke un char dans un tableau. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>castore</exemple>
			<opcode>85</opcode>
		</instruction>
		<instruction>
			<name>checkcast</name>
			<parameters>
				<parameter>indexbyte1</parameter>
				<parameter>indexbyte2</parameter>
			</parameters>
			<description>Checks whether an objectref is of a certain type, the class reference of which is in the constant pool at index (indexbyte1 &lt;&lt; 8 | indexbyte2)</description>
			<exemple>TODO</exemple>
			<opcode>192</opcode>
		</instruction>
		<instruction>
			<name>d2f</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction convertit une valeur de type double se trouvant au sommet de la stack vers le type float. Cette instruction ne prend aucun paramètre.</description>
 
			<exemple>d2f</exemple>
			<opcode>144</opcode>
		</instruction>
		<instruction>
			<name>d2i</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction convertit une valeur de type double se trouvant au sommet de la stack vers le type int. Cette instruction ne prend aucun paramètre.</description>
  
 
			<exemple>d2i</exemple>
			<opcode>142</opcode>
		</instruction>
		<instruction>
			<name>d2l</name>
			<parameters>
			</parameters>
  
		
			<description>Cette instruction convertit une valeur de type double se trouvant au sommet de la stack vers le type long. Cette instruction ne prend aucun paramètre.</description>
 
			<exemple>d2l</exemple>
			<opcode>143</opcode>
		</instruction>
		<instruction>
			<name>dadd</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction effectue une opération d'addition entre deux entiers de type double. Cette instruction ne prend aucun paramètre.</description>
  
			<exemple>dadd (Précédé de deux dload par exemple, l'opération d'addition sera effectuée).</exemple>
			<opcode>99</opcode>
		</instruction>
		<instruction>
			<name>daload</name>
			<parameters>
			</parameters>
  
		
  
			<description>Cette instruction charge un entier de type double depuis un tableau. Le tableau doit être de type double. Cette instruction ne prend aucun paramètre.</description>
 
			<exemple>daload</exemple>
			<opcode>49</opcode>
		</instruction>
		<instruction>
			<name>dastore</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction stocke un entier de type double dans un tableau. Le tableau doit être de type double. Cette instruction ne prend aucun paramètre.</description>
  
			
 
			<exemple>dastore (Précédé du tableau et de la valeur dastore l'ajoutera au tableau).</exemple>
			<opcode>82</opcode>
		</instruction>
		<instruction>
			<name>dcmpg</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction compare deux entiers de type double. Si la première valeur est supérieur à la deuxième la valeur de type int "1" est envoyée dans la stack. Cette instruction ne prend aucun paramètre.</description>
 
			<exemple>dcmpg (Compare deux entiers chargés précédemment par exemple).</exemple>
			<opcode>152</opcode>
		</instruction>
		<instruction>
			<name>dcmpl</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction compare deux entiers de type double. Si la première valeur est inférieur à la deuxième la valeur de type int "-1" est envoyée dans la stack. Cette instruction ne prend aucun paramètre.</description>
 
			<exemple>dcmpg (Compare deux entiers chargés précédemment par exemple).</exemple>
			<opcode>151</opcode>
		</instruction>
		<instruction>
			<name>dconst_0</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction stocke la valeur de type double "0" dans la stack. L'instruction ne prend rien en paramètre.</description>
 
			<exemple>dconst_0</exemple>
			<opcode>14</opcode>
		</instruction>
		<instruction>
			<name>dconst_1</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction stocke la valeur de type double "1" dans la stack. L'instruction ne prend rien en paramètre.</description>
 
			<exemple>dconst_1</exemple>
			<opcode>15</opcode>
		</instruction>
		<instruction>
			<name>ddiv</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction effectue l'opération division entre deux entiers de type double. Cette instruction ne prend aucun paramètre.</description>
			<exemple>ddiv (Précédé du chargement de deux entiers double effectue l'opération de division).</exemple>
 
			<opcode>111</opcode>
		</instruction>
		<instruction>
			<name>dload</name>
			<parameters>
				<parameter>index</parameter>
			</parameters>
  
			<description>Cette instruction charge un double #index donné en paramètre dans la stack. Index est de type unsigned byte.</description>
 
			<exemple>dload</exemple>
			<opcode>24</opcode>
		</instruction>
		<instruction>
			<name>dload_0</name>
			<parameters>
			</parameters>
  

  
			<description>Cette instruction charge un double depuis la variable locale 0 dans la stack. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>dload_0</exemple>
			<opcode>38</opcode>
		</instruction>
		<instruction>
			<name>dload_1</name>
			<parameters>
			</parameters>
  
	
  
			<description>Cette instruction charge un double depuis la variable locale 1 dans la stack. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>dload_1</exemple>
			<opcode>39</opcode>
		</instruction>
		<instruction>
			<name>dload_2</name>
			<parameters>
			</parameters>
  

  
			<description>Cette instruction charge un double depuis la variable locale 2 dans la stack. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>dload_3</exemple>
			<opcode>40</opcode>
		</instruction>
		<instruction>
			<name>dload_3</name>
			<parameters>
			</parameters>
  
			
  
			<description>Cette instruction charge un double depuis la variable locale 3 dans la stack. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>dload_3</exemple>
			<opcode>41</opcode>
		</instruction>
		<instruction>
			<name>dmul</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction effectue une opération de multiplication entre deux valeurs de type double. Cette instruction ne prend pas de paramètre</description>
			<exemple>dmul (Précédé de deux chargements de double l'instruction les multiplie et retournés sa valeur dans la stack).</exemple>
 
			<opcode>107</opcode>
		</instruction>
		<instruction>
			<name>dneg</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction rend une valeur de type double négative. Cette instruction ne prend pas de paramètre.</description>
			<exemple>dneg (L'instruction rend négative la dernière valeur ajoutée dans la stack).</exemple>
 
			<opcode>119</opcode>
		</instruction>
		<instruction>
			<name>drem</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction effectue une opération de division pour obtenir le reste entre deux valeurs de type double. Cette instruction ne prend pas de paramètre.</description>
			<exemple>drem (Précédé de deux chargements de double l'instruction effectue une division et retournés le reste dans la stack).</exemple>
 
			<opcode>115</opcode>
		</instruction>
		<instruction>
			<name>dreturn</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction retourne un double d'une méthode. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>dreturn</exemple>
			<opcode>175</opcode>
		</instruction>
		<instruction>
			<name>dstore</name>
			<parameters>
				<parameter>index</parameter>
			</parameters>
  

  
			<description>Cette instruction stocke une valeur de type double dans une variable locale donnée en paramètre #index.</description>
 
			<exemple>dstore</exemple>
			<opcode>57</opcode>
		</instruction>
		<instruction>
			<name>dstore_0</name>
			<parameters>
			</parameters>
  
			
  
			<description>Cette instruction stocke un double dans la variable locale dstore_0. Cette instruction ne prend pas de paramètre.</description>
			<exemple>dstore_0 (Précédé d'un bipush le store stocke la valeur donné par le bipush dans la variable locale).</exemple>
 
			<opcode>71</opcode>
		</instruction>
		<instruction>
			<name>dstore_1</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction stocke un double dans la variable locale dstore_1. Cette instruction ne prend pas de paramètre.</description>
			<exemple>dstore_11 (Précédé d'un bipush le store stocke la valeur donné par le bipush dans la variable locale).</exemple>
 
			<opcode>72</opcode>
		</instruction>
		<instruction>
			<name>dstore_2</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction stocke un double dans la variable locale dstore_2. Cette instruction ne prend pas de paramètre.</description>
			<exemple>dstore_2 (Précédé d'un bipush le store stocke la valeur donné par le bipush dans la variable locale).</exemple>
 
			<opcode>73</opcode>
		</instruction>
		<instruction>
			<name>dstore_3</name>
			<parameters>
			</parameters>
  
			
  
			<description>Cette instruction stocke un double dans la variable locale dstore_3. Cette instruction ne prend pas de paramètre.</description>
			<exemple>dstore_3 (Précédé d'un bipush le store stocke la valeur donné par le bipush dans la variable locale).</exemple>
 
			<opcode>74</opcode>
		</instruction>
		<instruction>
			<name>dsub</name>
			<parameters>
			</parameters>
  

  
			<description>Cette instruction effectue une opération de soustraction entre deux valeurs de type double au sommet de la stack. Cette instruction ne prend pas de paramètre.</description>
			<exemple>dsub (effectue la soustraction des deux valeurs de types double se situant au sommet de la stack).</exemple>
 
			<opcode>103</opcode>
		</instruction>
		<instruction>
			<name>dup</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction effectue une copie de la valeur se situant au sommet de la stack et la met dans la stack. Cette instruction ne prend pas de paramètre.</description>
  
			
 
			<exemple>dup</exemple>
			<opcode>89</opcode>
		</instruction>
		<instruction>
			<name>dup_x1</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction effectue une copie de la valeur se situant au sommet de la stack et la met dans la stack deux positions après le sommet. Cette instruction ne prend pas de paramètre.</description>
  
 
			<exemple>dup_x1</exemple>
			<opcode>90</opcode>
		</instruction>
		<instruction>
			<name>dup_x2</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction effectue une copie de la valeur se situant au sommet de la stack et la met dans la stack deux ou trois positions après le sommet. Cette instruction ne prend pas de paramètre.</description>
  
 
			<exemple>dup_x2</exemple>
			<opcode>91</opcode>
		</instruction>
		<instruction>
			<name>dup2</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction effectue une copie des deux valeurs du sommet de la stack et les place dans la stack dans l'ordre de leur copie. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>dup2</exemple>
			<opcode>92</opcode>
		</instruction>
		<instruction>
			<name>dup2_x1</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction effectue une copie des deux valeurs du sommet de la stack et les place dans la stack dans l'ordre de leur copie deux ou trois positions après le sommet. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>dup2_x1</exemple>
			<opcode>93</opcode>
		</instruction>
		<instruction>
			<name>dup2_x2</name>
			<parameters>
			</parameters>
  
			
  
			<description>Cette instruction effectue une copie des deux valeurs du sommet de la stack et les place dans la stack dans l'ordre de leur copie deux ou trois positions après le sommet. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>dup2_x2</exemple>
			<opcode>94</opcode>
		</instruction>
		<instruction>
			<name>f2d</name>
			<parameters>
			</parameters>
    
			<description>Cette instruction convertit un float en double. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>f2d</exemple>
			<opcode>141</opcode>
		</instruction>
		<instruction>
			<name>f2i</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction convertit un float en int. Cette instruction ne prend pas de paramètre.</description>
  
 
			<exemple>f2i</exemple>
			<opcode>139</opcode>
		</instruction>
		<instruction>
			<name>f2l</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction convertit un float en long. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>f2l</exemple>
			<opcode>140</opcode>
		</instruction>
		<instruction>
			<name>fadd</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction effectue une opération d'addition entre deux entiers de type float. Cette instruction ne prend aucun paramètre.</description>
 
			<exemple>fadd (Précédé de deux dload par exemple, l'opération d'addition sera effectuée).</exemple>
			<opcode>98</opcode>
		</instruction>
		<instruction>
			<name>faload</name>
			<parameters>
			</parameters>
  
		
  
			<description>Cette instruction charge un entier de type float depuis un tableau. Le tableau doit être de type float. Cette instruction ne prend aucun paramètre.</description>
 
			<exemple>faload</exemple>
			<opcode>48</opcode>
		</instruction>
		<instruction>
			<name>fastore</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction stocke un entier de type double dans un tableau. Le tableau doit être de type double. Cette instruction ne prend aucun paramètre.</description>
 
			<exemple>fastore (Précédé du tableau et de la valeur dastore l'ajoutera au tableau).</exemple>
			<opcode>81</opcode>
		</instruction>
		<instruction>
			<name>fcmpg</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction compare deux entiers de type float. Si la première valeur est supérieur à la deuxième la valeur de type int "1" est envoyée dans la stack. Cette instruction ne prend aucun paramètre.</description>
 
			<exemple>fcmpg</exemple>
			<opcode>150</opcode>
		</instruction>
		<instruction>
			<name>fcmpl</name>
			<parameters>
			</parameters>
  
			
  
			<description>Cette instruction compare deux entiers de type float. Si la première valeur est inférieur à la deuxième la valeur de type int "-1" est envoyée dans la stack. Cette instruction ne prend aucun paramètre.</description>
 
			<exemple>fcmpl</exemple>
			<opcode>149</opcode>
		</instruction>
		<instruction>
			<name>fconst_0</name>
			<parameters>
			</parameters>
    
			<description>Cette instruction stocke la valeur de type float "0" dans la stack. L'instruction ne prend rien en paramètre.</description>
 
			<exemple>fconst_0</exemple>
			<opcode>11</opcode>
		</instruction>
		<instruction>
			<name>fconst_1</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction stocke la valeur de type float "1" dans la stack. L'instruction ne prend rien en paramètre.</description>
 
			<exemple>fconst_1</exemple>
			<opcode>12</opcode>
		</instruction>
		<instruction>
			<name>fconst_2</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction stocke la valeur de type float "2" dans la stack. L'instruction ne prend rien en paramètre.</description>
 
			<exemple>fconst_2</exemple>
			<opcode>13</opcode>
		</instruction>
		<instruction>
			<name>fdiv</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction effectue l'opération division entre deux entiers de type float. Cette instruction ne prend aucun paramètre.</description>
			<exemple>fdiv (Précédé du chargement de deux entiers float effectue l'opération de division).</exemple>
 
			<opcode>110</opcode>
		</instruction>
		<instruction>
			<name>fload</name>
			<parameters>
				<parameter>index</parameter>
			</parameters>
    
			<description>Cette instruction charge un double #index donné en paramètre dans la stack. Index est de type unsigned byte.</description>
 
			<exemple>fload</exemple>
			<opcode>23</opcode>
		</instruction>
		<instruction>
			<name>fload_0</name>
			<parameters>
			</parameters>
    
			<description>Cette instruction charge un float depuis la variable locale 0 dans la stack. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>fload_0</exemple>
			<opcode>34</opcode>
		</instruction>
		<instruction>
			<name>fload_1</name>
			<parameters>
			</parameters>
    
			<description>Cette instruction charge un float depuis la variable locale 1 dans la stack. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>fload_1</exemple>
			<opcode>35</opcode>
		</instruction>
		<instruction>
			<name>fload_2</name>
			<parameters>
			</parameters>
    
			<description>Cette instruction charge un float depuis la variable locale 2 dans la stack. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>fload_2</exemple>
			<opcode>36</opcode>
		</instruction>
		<instruction>
			<name>fload_3</name>
			<parameters>
			</parameters>
    
			<description>Cette instruction charge un float depuis la variable locale 3 dans la stack. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>fload_3</exemple>
			<opcode>37</opcode>
		</instruction>
		<instruction>
			<name>fmul</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction effectue une opération de multiplication entre deux valeurs de type float. Cette instruction ne prend pas de paramètre</description>
			<exemple>fmul (Précédé de deux chargements de float l'instruction les multiplie et retournés sa valeur dans la stack).</exemple>
 
			<opcode>106</opcode>
		</instruction>
		<instruction>
			<name>fneg</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction rend une valeur de type float négative. Cette instruction ne prend pas de paramètre.</description>
			<exemple>fneg (L'instruction rend négative la dernière valeur de type float ajoutée dans la stack).</exemple>
 
			<opcode>118</opcode>
		</instruction>
		<instruction>
			<name>frem</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction effectue une opération de division pour obtenir le reste entre deux valeurs de type float. Cette instruction ne prend pas de paramètre.</description>
			<exemple>frem (Précédé de deux chargements de float l'instruction effectue une division et retournés le reste dans la stack).</exemple>
 
			<opcode>114</opcode>
		</instruction>
		<instruction>
			<name>freturn</name>
			<parameters>
			</parameters>
    
			<description>Cette instruction retourne un float d'une méthode. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>freturn</exemple>
			<opcode>174</opcode>
		</instruction>
		<instruction>
			<name>fstore</name>
			<parameters>
				<parameter>index</parameter>
			</parameters>
    
			<description>Cette instruction stocke une valeur de type float dans le paramètre #index. Cette instruction ne prend pas de paramètre.</description>
 
			<exemple>fstore</exemple>
			<opcode>56</opcode>
		</instruction>
		<instruction>
			<name>fstore_0</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction stocke un float dans la variable locale fstore_0. Cette instruction ne prend pas de paramètre.</description>
			<exemple>fstore_0 (Précédé d'un bipush le store stocke la valeur donné par le bipush dans la variable locale).</exemple>
 
			<opcode>67</opcode>
		</instruction>
		<instruction>
			<name>fstore_1</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction stocke un float dans la variable locale fstore_1. Cette instruction ne prend pas de paramètre.</description>
			<exemple>fstore_1 (Précédé d'un bipush le store stocke la valeur donné par le bipush dans la variable locale).</exemple>
 
			<opcode>68</opcode>
		</instruction>
		<instruction>
			<name>fstore_2</name>
			<parameters>
			</parameters>
  
			<description>Cette instruction stocke un float dans la variable locale fstore_2. Cette instruction ne prend pas de paramètre.</description>
			<exemple>fstore_2 (Précédé d'un bipush le store stocke la valeur donné par le bipush dans la variable locale).</exemple>
 
			<opcode>69</opcode>
		</instruction>
		<instruction>
			<name>fstore_3</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction stocke un float dans la variable locale fstore_3. Cette instruction ne prend pas de paramètre.</description>
			<exemple>fstore_3 (Précédé d'un bipush le store stocke la valeur donné par le bipush dans la variable locale).</exemple>
 
			<opcode>70</opcode>
		</instruction>
		<instruction>
			<name>fsub</name>
			<parameters>
			</parameters>
  
  
			<description>Cette instruction effectue une opération de soustraction entre deux valeurs de type double au sommet de la stack. Cette instruction ne prend pas de paramètre.</description>
			<exemple>fsub (effectue la soustraction des deux valeurs de types float se situant au sommet de la stack).</exemple>
 
			<opcode>102</opcode>
		</instruction>